version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: DockerfileProtgresql
    ports:
      - "5432:5432"
    volumes:
      - D:\Work_Space\Sring_Boot_WorkSpace\Predict_Postgress_Volume:/var/lib/postgresql/data

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/predictstock
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      POSTGRES_DB: predictStock

volumes:
  postgres-data:






